/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'a' at '9/3/16 11:10 PM' with Gradle 3.0
 *
 * @author a, @date 9/3/16 11:10 PM
 */
public class Library {
    

    public void sayHi() {
    	System.out.println("Hi my friend!!!");
    }

    public static void main(String[] args) {
    	
    }
}
