/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'a' at '9/1/16 11:42 PM' with Gradle 3.0
 *
 * @author a, @date 9/1/16 11:42 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
